# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import movie_recommender

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 550)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 170, 231, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 340, 511, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 260, 231, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(150, 60, 241, 101))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setPlaceholderText("Enter one movie per line.\nThe Terminator\nAvengers")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 310, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 121, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 220, 231, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Die Hard")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(lambda: self.getmoviereccomendation())
        self.pushButton_2.clicked.connect(lambda: self.getmovieinfo())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie Recommender System"))
        self.pushButton.setText(_translate("MainWindow", "Get Reccomendations"))
        self.label.setText(_translate("MainWindow", " "))
        self.pushButton_2.setText(_translate("MainWindow", "Get Movie Info."))
        self.label_2.setText(_translate("MainWindow", "Name of the Movies:"))
        self.label_3.setText(_translate("MainWindow", "Name of the Movie:"))
        self.label_4.setText(_translate("MainWindow", " Movie Recommender System"))
        self.label_5.setText(_translate("MainWindow", "Recommended Movies"))
    
    def getmoviereccomendation(self):
        movie_name=self.textEdit.toPlainText()
        movie_name=movie_name.split("\n")
        self.label_5.setText("Recommended Movies")
        self.label_5.adjustSize()
        final=movie_recommender.get_recommendations(movie_name)
        recommendations=''
        for x in final:
            recommendations=recommendations+str(x)+"\n"
        self.label.setText(recommendations)
        self.label.adjustSize()

    def getmovieinfo(self):
        movie_name=self.lineEdit.text()
        self.label_5.setText("Movie Details")
        self.label_5.adjustSize()
        final=movie_recommender.get_info(movie_name)
        self.label.setText(final)
        self.label.adjustSize()
        self.label.setWordWrap(True)

        
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
